sonar:
  build: .
  container_name: sonarqube
  links:
   - postgresql:postgresql
  ports:
   - "9000:9000"
  environment:
   - ADOP_LDAP_ENABLED=false
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar
   - SONARQUBE_WEB_CONTEXT=
   - LDAP_URL=${LDAP_URL}
   - LDAP_BIND_DN=${LDAP_BIND_DN}
   - LDAP_BIND_PASSWORD=${LDAP_PASSWORD}
   - LDAP_USER_BASE_DN=cn=$${username}
   - LDAP_USER_EMAIL_ATTRIBUTE=email
   - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonar
postgresql:
 image: postgres:10.8
 container_name: postgresql
 environment:
  - POSTGRES_USER=sonar
  - POSTGRES_PASSWORD=sonar
  - POSTGRES_DB=sonar
 ports:
  - "5432:5432"
